#!/bin/sh

exec 2>&1

(socat udp-recv:10110 pty,link=/dev/ttyUDP10110,raw,echo=0,b115200) &
exec /opt/victronenergy/gps-dbus/gps_dbus --banner --dbus system --timeout 60 -s /dev/ttyUDP10110 -b 115200
